#!/usr/bin/env python3
"""Tier-2 label survey table: binary critical-residue antigens from IEDB shotgun scans.

Reads the IEDB shotgun candidate list (benchmark/iedb_shotgun_candidates_v1.csv,
produced by analysis/fetch_iedb_shotgun.py) and emits a LaTeX survey table of the
simulatable, not-yet-included antigens whose labels are binary critical/non-critical
(saturating alanine scan read out by flow cytometry). This is the energetic-but-coarse
"second tier" complementing the graded ddG antigens.

Output: manuscript/sections/tables/binary_survey.tex
Run:    python3 analysis/make_binary_label_table.py
"""
import csv, pathlib

CSV = pathlib.Path("benchmark/iedb_shotgun_candidates_v1.csv")
OUT = pathlib.Path("manuscript/sections/tables/binary_survey.tex")

# Curated shortlist of simulatable Tier-2 candidates: (antigen substring, organism
# substring, display name, provisional structural handle). PDBs marked [v] are
# provisional reps to be confirmed before a run/figure (numbering must be verified
# against the critical-residue list, as for the ddG antigens).
SHORTLIST = [
    ("Genome polyprotein",        "Dengue",     "Dengue E (envelope)",   "sE ectodomain, e.g.\\ 1OKE [v]"),
    ("Structural polyprotein",    "chikungunya","Chikungunya E1/E2",     "ectodomain, e.g.\\ 3N42 [v]"),
    ("Envelopment polyprotein",   "Rift Valley","RVFV Gn",               "Gn ectodomain, e.g.\\ 6F9F [v]"),
    ("Hemagglutinin",             "Influenza",  "Influenza HA",          "HA ectodomain (trimeric) [v]"),
    ("Growth-regulated alpha",    "",           "GRO-$\\alpha$ / CXCL1", "chemokine, e.g.\\ 1MGS [v]"),
    ("T-cell surface glycoprotein CD4", "",     "CD4",                   "D1--D2, e.g.\\ 1CDH [v]"),
    ("CD40 ligand",               "",           "CD40L",                 "TNF domain, e.g.\\ 1ALY [v]"),
    ("Interleukin-2 receptor subunit alpha", "","IL-2R$\\alpha$",        "ectodomain, e.g.\\ 1Z92 [v]"),
    ("Interleukin-7 receptor subunit alpha", "","IL-7R$\\alpha$",        "ectodomain, e.g.\\ 3DI2 [v]"),
    ("HLA class I histocompatibility", "",      "HLA class I",           "peptide-MHC, many [v]"),
]


def esc(s):
    return s.replace("&", "\\&").replace("_", "\\_")


def main():
    rows = list(csv.DictReader(open(CSV)))
    def find(antigen_sub, org_sub):
        for r in rows:
            if antigen_sub.lower() in r["antigen"].lower() and org_sub.lower() in r["organism"].lower():
                return r
        return None

    L = ["% AUTO-GENERATED by analysis/make_binary_label_table.py -- do not edit by hand."]
    L.append("\\begin{table}[htbp]\\centering\\small")
    L.append("\\caption{\\textbf{Tier-2 (binary) label candidates} from IEDB shotgun-mutagenesis "
             "alanine scans (flow-cytometry critical-residue mapping; Integral Molecular / Doranz). "
             "Labels are per-residue \\emph{critical vs non-critical}, energetically grounded "
             "(a critical residue is one whose mutation measurably weakens antibody binding) but "
             "coarser than $\\ddG$. ``Antibodies'' = mapped antibody footprints (one antibody "
             "$\\to$ one conformational epitope); ``Studies'' = distinct source papers; ``Crit.\\ "
             "res.'' = union of critical residues across all antibodies. Structures provisional "
             "([v] = numbering to be verified before use).}")
    L.append("\\label{tab:binary-survey}")
    L.append("\\begin{tabular}{llrrrl}")
    L.append("\\toprule")
    L.append("Antigen & Organism & Antibodies & Studies & Crit.\\ res. & Structural handle \\\\")
    L.append("\\midrule")
    for antigen_sub, org_sub, disp, handle in SHORTLIST:
        r = find(antigen_sub, org_sub)
        if not r:
            continue
        L.append(f"{disp} & {esc(r['organism'])} & {r['n_antibodies']} & {r['n_studies']} & "
                 f"{r['n_critical_residues']} & {handle} \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
