#!/usr/bin/env python3
"""Generate per-antigen alanine-scan label tables (LaTeX) for the manuscript.

Reads the curated benchmark CSV and emits one booktabs table per simulated
antigen, with one ddG (change in binding free energy) column per antibody
complex. Every ddG is derived from a measured affinity (K_d) or inhibition
(K_i) constant via ddG = RT ln(K_mut/K_wt); stated per-table in the caption.

Output: manuscript/sections/label_tables.tex   (\\input from main.tex)
Run:    python3 analysis/make_label_tables.py
Recorded in manuscript/figures/FIGURES.md.
"""
import csv, collections, pathlib

CSV = pathlib.Path("benchmark/antigen_alanine_scan_extracted_SIMPLE_v1.csv")
OUTDIR = pathlib.Path("manuscript/sections/tables")  # one table fragment per antigen

# Antigens we are simulating (display order). 'key' = output filename stem (also the
# stem of the hand-written section file in sections/antigens/<key>.tex).
SIMULATED = {
    "Lysozyme":  dict(key="lysozyme", struct="apo 1AKI",                     qty="d", assay="SPR"),
    "HPr":       dict(key="hpr",      struct="strip 2JEL chain P",           qty="d", assay="competition"),
    "VEGF":      dict(key="vegf",     struct="strip 1BJ1 chains V,W (dimer)",qty="d", assay="SPR"),
    "MT-SP1":    dict(key="mtsp1",    struct="strip 3NPS chain A",           qty="i", assay="enzymatic inhibition"),
    "Bont/A1":   dict(key="bonta1",   struct="extract 2NYY Hc (res 872-1295)",qty="d", assay="KinExA"),
}

def esc(s):
    return s.replace("&", "\\&").replace("_", "\\_")

# Short, clean column labels for the verbose benchmark antibody names.
ABBREV = {
    "Neutralizing mAb (fab-12)":      "fab-12",
    "affinity matured mAb (Y0317)":   "Y0317",
    "mAb CR1":                        "CR1",
    "mAb AR2":                        "AR2",
    "Fab Inhibitor E2":               "E2",
    "Fab Inhibitor S4":               "S4",
    "Jel42 antibody":                 "Jel42",
    "HYHEL-63":                       "HyHEL-63",
    "HyHEL-10 Fv":                    "HyHEL-10",
    "IgG1-kappa D1.3 Fv":             "D1.3",
}
def ab_short(ab):
    return ABBREV.get(ab, ab)

rows = [r for r in csv.DictReader(open(CSV))
        if r["Use for MD correlation?"].startswith("YES")
        and r["Antigen"].strip() in SIMULATED]

by_ag = collections.defaultdict(lambda: {"complexes": [], "res": {}})
seen = collections.defaultdict(set)
for r in rows:
    ag = r["Antigen"].strip(); pdb = r["PDB/model"].strip()
    if pdb not in seen[ag]:
        seen[ag].add(pdb); by_ag[ag]["complexes"].append((pdb, r["Antibody"].strip()))
    try:
        resi = int(r["Residue #"]); ddg = float(r["Best ΔΔG kcal/mol"])
    except ValueError:
        continue
    res = by_ag[ag]["res"].setdefault(resi, {"wt": r["WT"].strip(), "vals": {}})
    res["vals"][pdb] = ddg

OUTDIR.mkdir(parents=True, exist_ok=True)
for ag, info in SIMULATED.items():
    if ag not in by_ag: continue
    cplx = by_ag[ag]["complexes"]; resmap = by_ag[ag]["res"]; n = len(cplx)
    L = ["% AUTO-GENERATED by analysis/make_label_tables.py -- do not edit by hand."]
    L.append("\\begin{table}[htbp]\\centering\\small")
    L.append(f"\\caption{{\\textbf{{{esc(ag)}}} alanine-scan \\ddG\\ (kcal/mol; "
             f"{esc(info['assay'])}, $K_{info['qty']}$-derived via "
             f"$\\ddG=RT\\ln(K^{{\\mathrm{{mut}}}}/K^{{\\mathrm{{wt}}}})$, $T=310$\\,K; "
             f"start structure: {esc(info['struct'])}). Positive \\ddG\\ weakens binding.}}")
    L.append(f"\\label{{tab:ddg-{info['key']}}}")
    L.append("\\begin{tabular}{l" + "r"*n + "}")
    L.append("\\toprule")
    L.append("Residue & " + " & ".join(f"{esc(ab_short(ab))} ({esc(pdb)})" for pdb, ab in cplx) + " \\\\")
    L.append("\\midrule")
    for resi in sorted(resmap):
        wt = resmap[resi]["wt"]; vals = resmap[resi]["vals"]
        cells = [f"{esc(wt)}{resi}"]
        for pdb, _ in cplx:
            cells.append(f"{vals[pdb]:+.2f}" if pdb in vals else "--")
        L.append(" & ".join(cells) + " \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    (OUTDIR / f"{info['key']}.tex").write_text("\n".join(L) + "\n")

print(f"wrote {len(by_ag)} table fragments to {OUTDIR}/")
for ag, info in SIMULATED.items():
    if ag in by_ag:
        print(f"  {info['key']:9} <- {ag:10} complexes={[c[0] for c in by_ag[ag]['complexes']]} "
              f"residues={len(by_ag[ag]['res'])}")
