#!/usr/bin/env python3
"""Generate per-antigen alanine-scan label tables (LaTeX) for the manuscript.

Reads the curated benchmark CSV and emits one booktabs table per simulated
antigen, with one ddG (change in binding free energy) column per antibody
complex. Every ddG is derived from a measured affinity (K_d) or inhibition
(K_i) constant via ddG = RT ln(K_mut/K_wt); stated per-table in the caption.

Output: manuscript/sections/label_tables.tex   (\\input from main.tex)
Run:    python3 analysis/make_label_tables.py
Recorded in manuscript/figures/FIGURES.md.
"""
import csv, collections, pathlib

CSV = pathlib.Path("benchmark/antigen_alanine_scan_extracted_SIMPLE_v1.csv")
OUT = pathlib.Path("manuscript/sections/label_tables.tex")

# Antigens we are simulating (display order), with start-structure + quantity notes.
SIMULATED = {
    "Lysozyme":  dict(struct="apo 1AKI (running)",             qty="d", assay="SPR"),
    "HPr":       dict(struct="strip 2JEL chain P",             qty="d", assay="competition"),
    "VEGF":      dict(struct="strip 1BJ1 chains V,W (dimer)",  qty="d", assay="SPR"),
    "MT-SP1":    dict(struct="strip 3NPS chain A",             qty="i", assay="enzymatic inhibition"),
    "Bont/A1":   dict(struct="extract 2NYY Hc (res 872-1295)", qty="d", assay="KinExA"),
}

def esc(s):
    return s.replace("&", "\\&").replace("_", "\\_")

rows = [r for r in csv.DictReader(open(CSV))
        if r["Use for MD correlation?"].startswith("YES")
        and r["Antigen"].strip() in SIMULATED]

by_ag = collections.defaultdict(lambda: {"complexes": [], "res": {}})
seen = collections.defaultdict(set)
for r in rows:
    ag = r["Antigen"].strip(); pdb = r["PDB/model"].strip()
    if pdb not in seen[ag]:
        seen[ag].add(pdb); by_ag[ag]["complexes"].append((pdb, r["Antibody"].strip()))
    try:
        resi = int(r["Residue #"]); ddg = float(r["Best ΔΔG kcal/mol"])
    except ValueError:
        continue
    res = by_ag[ag]["res"].setdefault(resi, {"wt": r["WT"].strip(), "vals": {}})
    res["vals"][pdb] = ddg

L = []
L.append("% AUTO-GENERATED by analysis/make_label_tables.py -- do not edit by hand.")
L.append("\\section{Benchmark labels by simulated antigen}")
L.append("")
L.append("Per-antigen alanine-scan labels (mutation to alanine) for the systems we simulate. "
         "Each value is the change in binding free energy \\ddG\\ in kcal/mol, derived from the "
         "measured affinity ($K_d$) or inhibition ($K_i$) constant via "
         "$\\ddG = RT\\ln(K^{\\mathrm{mut}}/K^{\\mathrm{wt}})$ at $T=310$\\,K "
         "($RT=0.616$\\,kcal/mol). Positive \\ddG\\ = mutation weakens binding; one column per "
         "antibody scanned against that antigen.")
L.append("")

for ag, info in SIMULATED.items():
    if ag not in by_ag: continue
    cplx = by_ag[ag]["complexes"]; resmap = by_ag[ag]["res"]; n = len(cplx)
    L.append("\\begin{table}[htbp]\\centering\\small")
    L.append(f"\\caption{{\\textbf{{{esc(ag)}}} alanine-scan \\ddG\\ (kcal/mol; "
             f"{esc(info['assay'])}, $K_{info['qty']}$-derived; start structure: "
             f"{esc(info['struct'])}).}}")
    L.append("\\begin{tabular}{l" + "r"*n + "}")
    L.append("\\toprule")
    L.append("Residue & " + " & ".join(f"{esc(ab)} ({esc(pdb)})" for pdb, ab in cplx) + " \\\\")
    L.append("\\midrule")
    for resi in sorted(resmap):
        wt = resmap[resi]["wt"]; vals = resmap[resi]["vals"]
        cells = [f"{esc(wt)}{resi}"]
        for pdb, _ in cplx:
            cells.append(f"{vals[pdb]:+.2f}" if pdb in vals else "--")
        L.append(" & ".join(cells) + " \\\\")
    L.append("\\bottomrule")
    L.append("\\end{tabular}")
    L.append("\\end{table}")
    L.append("")

OUT.write_text("\n".join(L))
print(f"wrote {OUT} ({len(rows)} label rows, {len(by_ag)} antigens)")
for ag in SIMULATED:
    if ag in by_ag:
        print(f"  {ag:10} complexes={[c[0] for c in by_ag[ag]['complexes']]} "
              f"residues={len(by_ag[ag]['res'])}")
